### PR TITLE
abstract branding

### PR DESCRIPTION
**Pull request by clif-os**
- adds readme for customizing coloring and branding images
- abstract css colors to a single css file
- use fostive branding

Screen Shot 2020-09-24 at 8 38 50 PM
Screen Shot 2020-09-24 at 8 41 19 PM

### CODE REVIEW

**Comment by superhighfives** [comment]
This is awesome, @clif-os! I think it'd be great to add a little more context to the branding readme, (heading, links to GitHub, an explanation of what can be branded followed by the details for each). cc @justjenu

**Comment by clif-os** [comment]
@superhighfives that sounds good. what do u mean by github links sorry?

**Comment by superhighfives** [comment]
Was thinking links to the different aspects of the GitHub repo / back to the FOSTIVE org, but can ignore @clif-os as @DianaPerkinsDesign is going to help out with this one. Thanks! 🙌

**Review by crcastle — APPROVED** [review]
Looks good @clif-os ! Please merge it!

**Pull request merged**
